### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by SolidSnke** [itsryuku/rumbotv3#1]
Did you get a chance to rewrite this??

**Comment by itsryuku** [comment]
Hi,

it was working but retrieving IDs is slow because we don't generate them; we retrieve them from Rumble one by one. Now, I've updated it to let the user know how many IDs have been retrieved, and you can see if the viewbots are being accepted or rejected by using the -v flag.

And yes, I am willing to rewrite it in Golang, but unfortunately, I haven't had any spare time for it yet.
